### ISSUE TITLE
Error on project creation

### ISSUE THREAD

**Issue by psugihara** [coreh-deprecated/nide#2]
I'm getting the following error when I create a project:

/usr/local/lib/node_modules/nide/node_modules/findit/node_modules/seq/index.js:76
        f.apply(cb, context.stack);
          ^
RangeError: Maximum call stack size exceeded
    at Function.APPLY_OVERFLOW (native)
    at action (/usr/local/lib/node_modules/nide/node_modules/findit/node_modules/seq/index.js:76:11)
    at next (/usr/local/lib/node_modules/nide/node_modules/findit/node_modules/seq/index.js:208:17)
    at /usr/local/lib/node_modules/nide/node_modules/findit/node_modules/seq/index.js:213:30
    at /usr/local/lib/node_modules/nide/node_modules/findit/node_modules/seq/index.js:55:24
    at Function.<anonymous> (/usr/local/lib/node_modules/nide/node_modules/findit/index.js:40:25)
    at Function.<anonymous> (/usr/local/lib/node_modules/nide/node_modules/findit/node_modules/seq/index.js:210:38)
    at action (/usr/local/lib/node_modules/nide/node_modules/findit/node_modules/seq/index.js:76:11)
    at next (/usr/local/lib/node_modules/nide/node_modules/findit/node_modules/seq/index.js:208:17)
    at /usr/local/lib/node_modules/nide/node_modules/findit/node_modules/seq/index.js:213:30'''

**Comment by coreh** [comment]
Woah, it seems this is a problem with `findit`, the library I'm using to recurse subdirectories.

Are you running `nide init` on an empty folder? Or does it contain files and other folders already?

Also, is there something strange about the path? (perhaps spaces, or special characters?)

Does the folder cointain symlinks?

**Comment by psugihara** [comment]
I was running it in my home folder. It worked great when I ran it in a new directory. Perhaps it should be more prominent in the README that nide needs a clean project directory.

This should definitely throw a better error faster.

Great work though!

**Comment by coreh** [comment]
The thing is, it should work on a directory with existing contents... The problem might be related to specific types of contents, such as symbolic links. Reading through the logs of the test instance I set up for Node KO revealed the app crashed once because of the same error.

**Comment by coreh** [comment]
Now that nide uses dive instead of find-it, this issue seems to be fixed. (Thanks pvorb!)
