### ISSUE TITLE
Error while installing with command line

### ISSUE THREAD

**Issue by ghost** [coreh-deprecated/nide#44]
Hi, I have a problem when installing nide "sudo install-g nper nide". Here is a log of errors

npm http GET https://registry.npmjs.org/nide
npm http 304 https://registry.npmjs.org/nide

npm ERR! Error: No compatible version found: nide
npm ERR! No valid targets found.
npm ERR! Perhaps not compatible with your version of node?
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/local/lib/node_modules/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache.js:415:44)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:231:7)
npm ERR! You may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "nide"
npm ERR! cwd /Users/xxxx/Projects/node
npm ERR! node -v v0.7.7-pre
npm ERR! npm -v 1.1.1
npm ERR! message No compatible version found: nide
npm ERR! message No valid targets found.
npm ERR! message Perhaps not compatible with your version of node?
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/xxxx/Projects/node/npm-debug.log
npm not ok

**Comment by aegypius** [comment]
Hi @igorissen ! 

Your node version is 0.7.7-pre, nide will run in any 0.6.x but not on 0.7 yet. 

A lot of modules are in this state at the moment. I would suggest you to downgrade your node version to 0.6.15 (which is the current stable version).
