### ISSUE TITLE
Strange Installation Errors

### ISSUE THREAD

**Issue by Marak** [coreh-deprecated/nide#5]
When installing `nide` going....

First, it took many npm installs before the npm install actually worked, not sure what caused this....

see: https://gist.github.com/c1285a01093bdbfb8a1a

I was able to eventually get it working.

**Comment by coreh** [comment]
Hmmm this could be because I used `'node': '~v0.4.9'` on the Engine section of my package.json. Some people reported problems with that, so we changed it to `'node': '~0.4.9'`...

It could also be a NPM bug, as the error log asks you to report it to the NPM devs:

```
ERR! Error: EAFNOSUPPORT, Address family not supported by protocol family
ERR!     at doConnect (net.js:555:5)
ERR!     at net.js:725:9
ERR!     at dns.js:196:34
ERR!     at IOWatcher.callback (dns.js:74:15)
ERR! Report this *entire* log at:
ERR!     <http://github.com/isaacs/npm/issues>
ERR! or email it to:
ERR!     <npm-@googlegroups.com>
```

**Comment by egeozcan** [comment]
Using Node.js v0.6.3, installed through nvm. Can't even use sudo with an nvm install. I get the following when I do _npm install -g nide_

```
npm ERR! TypeError: Bad argument
npm ERR!     at Object._open (fs.js:224:11)
npm ERR!     at open (/home/ege/.nvm/v0.6.3/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:73:6)
npm ERR!     at Object.open (/home/ege/.nvm/v0.6.3/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:67:3)
npm ERR!     at Object.lutimes (/home/ege/.nvm/v0.6.3/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:28:6)
npm ERR!     at setProps (/home/ege/.nvm/v0.6.3/lib/node_modules/npm/node_modules/fstream/lib/writer.js:267:18)
npm ERR!     at Object.oncomplete (/home/ege/.nvm/v0.6.3/lib/node_modules/npm/node_modules/fstream/lib/writer.js:205:7)
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Linux 2.6.38-11-generic
npm ERR! command "node" "/home/ege/.nvm/v0.6.3/bin/npm" "install" "-g" "nide"
npm ERR! cwd /home/ege/workspace/fstest
npm ERR! node -v v0.6.3
npm ERR! npm -v 1.1.0-alpha-2
npm ERR! message Bad argument
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ege/workspace/fstest/npm-debug.log
npm not ok
```

**Comment by coreh** [comment]
Hey @egeozcan,

Are other packages installing normally? This seems like a NPM problem to me (since NPM is instructing you to report the bug to their issue tracker). Perhaps this particular setup with NVM is breaking NPM?

**Comment by egeozcan** [comment]
@Coreh
Thanks for the suggestion. My first reaction was to listen to my gut-feeling and think that this problem is caused by nide needing su rights... Had no problems with the other plug-ins but I'll report it on NPM bug-tracker anyway.

edit: here it is, https://github.com/isaacs/npm/issues/1826

**Comment by coreh** [comment]
<del>Installing nide does not require any super user rights.</del> **Edit:** Actually, it does, since you'd want it installed globally. What I meant is that we do not use any sort of install script. Super user rights are only required by nide itself if you want to run the IDE on a lower port, or if you need access to a folder your user has no permission.

I'm watching the issue you just created there. If it turns out I've done something wrong with the packaging, and that's breaking the install on some specific setups, I'll try to fix it ASAP.

**Comment by egeozcan** [comment]
Issue tracker is not the right place for this, I know, but I must say I'm very impressed with nide, especially considering the development time. Congratulations. I hope I can contribute to this project in the future.

Back to the topic... I upgraded to Nodejs v0.6.4 and the problem disappeared. By the way, I installed nide without su rights but it still works perfectly (as long as you don't try to change the port as you said -- had to disable nginx to make it work).

I'd vote for closing the issue but I guess we don't know how it went for @Marak.

**Comment by eth0lo** [comment]
Hi I'm having an issue similar to the one from @egeozcan 

``` bash
npm ERR! TypeError: Cannot call method 'call' of undefined
npm ERR!     at Object.lchown (/usr/lib/nodejs/npm/node_modules/graceful-fs/graceful-fs.js:228:17)
npm ERR!     at setProps (/usr/lib/nodejs/npm/node_modules/fstream/lib/writer.js:240:19)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/npm/node_modules/fstream/lib/writer.js:206:7)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Linux 3.0.0-15-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "nide"
npm ERR! cwd /home/scsi
npm ERR! node -v v0.6.9
npm ERR! npm -v 1.1.0-2
npm ERR! type non_object_property_call
npm ERR! arguments [ 'call', undefined ]
npm ERR! message Cannot call method 'call' of undefined
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/scsi/npm-debug.log
```
