### ISSUE TITLE
Internal error at the local server

### ISSUE THREAD

**Issue by mazhar266** [coreh-deprecated/nide#83]
Whenever I try to open a project on the Mac version of the app it shows:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Command failed: /bin/sh -c npm ls
npm ERR! extraneous: path@0.4.9 /Users/mazhar/Desktop/mdk/node_modules/path
npm ERR! extraneous: express@4.4.5 /Users/mazhar/Desktop/mdk/node_modules/express
npm ERR! extraneous: tiny-lr@0.0.7 /Users/mazhar/Desktop/mdk/node_modules/tiny-lr
npm ERR! not ok code 0

    at ChildProcess.exithandler (child_process.js:729:12)
    at ChildProcess.EventEmitter.emit (events.js:110:17)
    at maybeClose (child_process.js:992:16)
    at Socket.<anonymous> (child_process.js:1142:11)
    at Socket.EventEmitter.emit (events.js:107:17)
    at Pipe.close (net.js:461:12)
```

If I run nide listen from the shell (previously run nide init) it shows me:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Command failed: /bin/sh -c npm ls
npm ERR! extraneous: koa-generic-session@1.0.0 /Users/mazhar/madefreshly-3/node_modules/koa-generic-session
npm ERR! extraneous: koa-static@1.4.5 /Users/mazhar/madefreshly-3/node_modules/koa-static
npm ERR! not ok code 0

    at ChildProcess.exithandler (child_process.js:729:12)
    at ChildProcess.EventEmitter.emit (events.js:110:17)
    at maybeClose (child_process.js:992:16)
    at Socket.<anonymous> (child_process.js:1142:11)
    at Socket.EventEmitter.emit (events.js:107:17)
    at Pipe.close (net.js:461:12)
```

**Comment by mazhar266** [comment]
My Node.js version is 0.11.13 and I'm running Mac OSX Mavericks.

**Comment by Macroyep** [comment]
/Applications/Nide.app/Contents/Resources/main.js:37
        if (dir && !path.existsSync(dir)) {
                         ^

TypeError: path.existsSync is not a function
    at /Applications/Nide.app/Contents/Resources/main.js:37:26
    at /Applications/Nide.app/Contents/Resources/main.js:18:13
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
